"""added recipe model

Revision ID: 61445740c35d
Revises: 7bae1c3396e9
Create Date: 2023-03-28 14:54:31.473728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61445740c35d'
down_revision = '7bae1c3396e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('complexity', sa.Enum('EASY', 'MEDIUM', 'HARD', name='recipecomplexity'), nullable=False),
    sa.Column('cooking_time', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
